// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj2AvBWu-PDOFdQ6e7qHE_wt2tYYI18dI',
    appId: '1:106005185468:web:efdeb4324a66642bb9a1b9',
    messagingSenderId: '106005185468',
    projectId: 'wise-agend',
    authDomain: 'wise-agend.firebaseapp.com',
    storageBucket: 'wise-agend.firebasestorage.app',
    measurementId: 'G-CRTYMVMXQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxOMrb1lFaxs8pCdSLVrZ17KIlL9kE81w',
    appId: '1:106005185468:android:0af6abaade30b56fb9a1b9',
    messagingSenderId: '106005185468',
    projectId: 'wise-agend',
    storageBucket: 'wise-agend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2iJnpKV_kYZW2VBgjfeWVSywwj67M4eI',
    appId: '1:106005185468:ios:a5d0ad3aa41bf9f4b9a1b9',
    messagingSenderId: '106005185468',
    projectId: 'wise-agend',
    storageBucket: 'wise-agend.firebasestorage.app',
    iosBundleId: 'com.example.wiseAgendPlantillaBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2iJnpKV_kYZW2VBgjfeWVSywwj67M4eI',
    appId: '1:106005185468:ios:a5d0ad3aa41bf9f4b9a1b9',
    messagingSenderId: '106005185468',
    projectId: 'wise-agend',
    storageBucket: 'wise-agend.firebasestorage.app',
    iosBundleId: 'com.example.wiseAgendPlantillaBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj2AvBWu-PDOFdQ6e7qHE_wt2tYYI18dI',
    appId: '1:106005185468:web:3e827b1219ec50b3b9a1b9',
    messagingSenderId: '106005185468',
    projectId: 'wise-agend',
    authDomain: 'wise-agend.firebaseapp.com',
    storageBucket: 'wise-agend.firebasestorage.app',
    measurementId: 'G-4Q8CBHF0MM',
  );
}
